# Generated by Django 5.2.1 on 2025-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_username_ticket_alter_ticket_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
